name: Build backend
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"
      - name: Build
        working-directory: ./src/Backend
        run: dotnet build --configuration Release
      # To make the backend enterprise-grade secure
      - name: Security Scan
        working-directory: ./src/Backend
        run: |
          dotnet list package --vulnerable --include-transitive
      - name: Static Code Analysis
        working-directory: ./src/Backend
        run: |
          dotnet tool install --global security-scan
          security-scan ./src/Backend