name: Build frontend
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - name: Build frontend
        working-directory: ./src/Frontend
        run: |
          npm install
          npm run build