name: Test frontend
on: push
jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   steps: 
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #     - name: Use node.js
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: '18.x'
  #     - name: Build frontend
  #       working-directory: ./src/Frontend
  #       run: |
  #         npm install
  #         npm run build
  # unit-test: 
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps: 
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #     - name: Use node.js
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: '18.x'
  #     - name: Build frontend
  #       working-directory: ./src/Frontend
  #       run: |
  #         npm install
  #         CI=true npm test
  e2e-test:
    # needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"
      - name: Build and run backend
        working-directory: ./src/Backend
        run: |
          dotnet build --configuration Release
          nohup dotnet run --configuration Release
          curl -k -v https://localhost:5000/Data
      - name: Build and run frontend
        working-directory: ./src/Frontend
        run: |
          npm install
          npm run build
          nohup npm start
          curl -k -v https://localhost:3000
      - name: Run E2E tests
        working-directory: ./src/Frontend/tests
        run: |
          npm install
          npx playwright install
          npm test